import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CraftCard from "./CraftCard";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {

  const [data, setData] = useState({});
  const [player, setPlayer] = useState({})
  const [loading, setLoading] = useState(false);

  useEffect(()=>{
          fetch("/api/data")
          .then(res => res.json())
          .then(data => {setData(data); setLoading(true); setPlayer(data?.player)})
  }, [])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
      {
        loading 
        ? <div className="App">
        <CraftCard item={data?.craft?.testItem} player={player}></CraftCard>
        </div>
        :<h1>Загрузка</h1>
      }
      </div>
    </>
  );
}
